### ISSUE TITLE
LABELMAXSCALE Deprecated

### ISSUE THREAD

**Issue by andrewteg** [szinggeler/SublimeMapfileSyntax#1]
I am using this and it's been great. I did notice that LABELMAXSCALE could possibly be added to the deprecated list.  I'm guessing LABELMINSCALE could be added too, though it seems they were deprecated quite a long time ago from https://mapserver.org/mapfile/layer.html

Thanks again for a lifesaver!
Andrew

**Comment by szinggeler** [comment]
Thanks for your hint! Since I rarely write mapfiles I have not adjusted anything for 3 years. I've made a few changes now. I hope I introduced no additional errors. ;-)

Stephan
